global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'starlink'
    scrape_interval: 3s
    scrape_timeout:  3s
    static_configs:
      - targets: ['starlink_exporter:9817']

  - job_name: 'speedtest'
    scrape_interval: 60m
    scrape_timeout: 70s
    static_configs:
      - targets: [ 'speedtest_exporter:9090' ]

  - job_name: 'blackbox'
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets: [ 'ping-naw.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_NA-West'
      - targets: [ 'ping-nae.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_NA-East'
      - targets: [ 'ping-eu.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_Europe'
      - targets: [ 'ping-oce.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_Oceania'
      - targets: [ 'ping-asia.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_Asia'
      - targets: [ 'ping-br.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_Brazil'
      - targets: [ 'ping-me.ds.on.epicgames.com' ]
        labels:
          name: 'epicgames_Middle-East'
      - targets: [ '8.8.8.8' ]
        labels:
          name: 'google_a'
      - targets: [ '8.8.4.4' ]
        labels:
          name: 'google_b'
      - targets: [ '1.1.1.1' ]
        labels:
          name: 'cloudflare'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
